### ISSUE TITLE
Feature requirement

### ISSUE THREAD

**Issue by edotappstore** [voxeet/voxeet-uxkit-react#220]
Hi @FabienLavocat 

I have used this plugin to share the file presentation in our client project, recently client came up with a requirement where in we need to manange the slides we are presenting to the end user as below

![image](https://user-images.githubusercontent.com/98312418/169277787-c74d4387-83fa-4ab4-bcaa-31ed01f61ae9.png)

From the above image add button will be used to **ADD** a presentaion in between 2 slides and **Delete** button will be used to delete a particular slide.
**Hide Slide** button will prevent/alllow the slide to be shown to the listerner.

Is this achivable using this plugin?

Thank you

**Comment by FabienLavocat** [comment]
@edotappstore this is something very interesting.

I would not use the UXKit for that particular functionality you are trying to build, but only for sharing the presentation itself. Instead, if you want to use it in the browser, I would eventually build the presentation locally (still in your web application), generate the PPTX and then send it to the Dolby.io platform for presentation to the audience. Because PPTX are opened format, I was able to use this [powerpoint.ts](https://github.com/dolbyio-samples/dolbyio-web-file-presentation-service/blob/main/client/services/powerpoint.js) file to parse an existing file and extract information from it. You can follow the same idea to generate a new presentation.

**Resource:** https://github.com/dolbyio-samples/dolbyio-web-file-presentation-service

**Comment by edotappstore** [comment]
@FabienLavocat thanks for the helpful advice
